name: POST API Call Every 10 Minutes
on:
  schedule:
    - cron: '*/10 * * * *'  
jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Make POST Request
        run: |
          curl -X POST "${{ secrets.API_ENDPOINT}}" \
            -H "Content-Type: application/json" \
            -d '{"key": "value"}'
