name: Periodic API Call
on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:  # Allow manual trigger
  push:
    branches: [main]  # Also trigger on push to main to verify it works

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Make POST Request
        run: |
          curl -X POST "${{ secrets.API_ENDPOINT}}" \
            -H "Content-Type: application/json" \
            -w "\n\nStatus Code: %{http_code}\n" \
            -o response.txt || true
          
          echo "Response:"
          cat response.txt || true
          
          STATUS=$(cat response.txt | grep "Status Code:" | cut -d' ' -f3)
          if [ "$STATUS" != "200" ]; then
            echo "API call failed with status: $STATUS"
          else
            echo "API call successful"
          fi
